Repository cloudfoundry-incubator/kubo-release, pull requests merged in 2018-03, with the labels that each got.

#178 Allows MutatingAdmissionWebhook admission controller by default
  jobs/kube-apiserver/templates/config/bpm.yml.erb
  spec/kube_apiserver_bpm_yml_spec.rb
Labels: unscheduled

#184 kube-controller-manager: ca.pem remove new line
  jobs/kube-controller-manager/templates/config/ca.pem.erb
Labels: unscheduled

#186 kubernetes upgrade v1.9.4
  config/blobs.yml
  jobs/apply-specs/templates/specs/influxdb.yml.erb
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: scheduled

#188 kubernetes upgrade v1.9.5
  config/blobs.yml
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: in progress

#189 kubernetes upgrade v1.9.6
  config/blobs.yml
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: unscheduled
