Repository cloudfoundry-incubator/kubo-release, pull requests merged in 2018-06, with the labels that each got.

#179 Generate Kubelet certificates with TLS bootstrap
  jobs/apply-specs/spec
  jobs/apply-specs/templates/specs/heapster.yml.erb
  jobs/kube-apiserver/spec
  jobs/kube-apiserver/templates/bin/ensure_apiserver_healthy.erb
  jobs/kube-apiserver/templates/config/bpm.yml.erb
  jobs/kube-apiserver/templates/config/kubernetes-ca.pem.erb
  jobs/kube-apiserver/templates/config/kubernetes.pem.erb
  jobs/kube-apiserver/templates/config/tokens.csv.erb
  jobs/kube-controller-manager/spec
  jobs/kube-controller-manager/templates/config/bpm.yml.erb
  jobs/kube-controller-manager/templates/config/ca.pem.erb
  jobs/kubelet/spec
  jobs/kubelet/templates/bin/ensure_kubelet_up_and_running.erb
  jobs/kubelet/templates/bin/kubelet_ctl.erb
  jobs/kubelet/templates/bin/post-start.erb
  jobs/kubelet/templates/config/admin-kubeconfig.erb
  jobs/kubelet/templates/config/bootstrap-kubeconfig.erb
  jobs/kubelet/templates/config/kubelet-key.pem.erb
  jobs/kubelet/templates/config/kubelet.pem.erb
  jobs/kubelet/templates/config/kubeletconfig.yml.erb
  jobs/kubernetes-roles/spec
  jobs/kubernetes-roles/templates/config/policies/bootstrap.yml
  jobs/kubernetes-roles/templates/config/policies/csr_cleaner.yml
  spec/kube_apiserver_bpm_yml_spec.rb
Labels: in progress

#210 kubernetes upgrade v1.10.4
  config/blobs.yml
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: scheduled

#217 Added templates for issues and pull requests
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: unscheduled
