Repository cloudfoundry-incubator/kubo-release, pull requests merged in 2018-08, with the labels that each got.

#239 kubernetes upgrade v1.11.2
  config/blobs.yml
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: scheduled

#221 Value ending in : break bpm yaml parsing and make kube-apiserver fail
  jobs/kube-apiserver/templates/config/bpm.yml.erb
  spec/kube_apiserver_bpm_yml_spec.rb
Labels: unscheduled

#233 Enable hostPort feature in CFCR
  config/blobs.yml
  jobs/flanneld/templates/bin/flanneld_ctl.erb
  packages/cni/packaging
  packages/cni/spec
Labels: in progress
