Repository cloudfoundry-incubator/kubo-release, pull requests merged in 2018-11, with the labels that each got.

#271 Bump k8s 1.12.2
  config/blobs.yml
  jobs/kube-controller-manager/spec
  jobs/kube-controller-manager/templates/config/kube-controller-manager-cert.pem.erb
  jobs/kube-controller-manager/templates/config/kube-controller-manager-private-key.pem.erb
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: unscheduled

#274 fix CONTRIBUTING.md integration-tests dir name error
  CONTRIBUTING.md
Labels: unscheduled

#276 Added backslash to end of kubelet's hardwired config flag
  jobs/kubelet/templates/bin/kubelet_ctl.erb
Labels: delivered

#278 Revert 274 patch 1
  CONTRIBUTING.md
Labels: unscheduled

#280 create PodSecurityPolicy doc page
  docs/pod-security-policy-walkthrough.md
Labels: unscheduled

#279 Enable Data Encryption at rest with config yaml file
  jobs/kube-apiserver/spec
  jobs/kube-apiserver/templates/config/encryption-config.yml.erb
Labels: unscheduled

#281 kubernetes upgrade v1.12.3
  config/blobs.yml
  packages/kubernetes/packaging
  packages/kubernetes/spec
Labels: in progress
